apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: my-alert
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  groups:
    - name: my-alert
      rules:
        - alert: im-db nede (test)
          expr: sum by (app, container, pod, namespace) (floor(increase(logback_events_total{app="im-db", level="info"} [1h]))) > 0
          for: 5m
          annotations:
            consequence: Application is unavailable
            action: "`kubectl describe pod <podname>` -> `kubectl logs <podname>`"
            summary: |-
              This is a multi-line summary with
              linebreaks and everything. Here you can give a more detailed
              summary of what this alert is about
          labels:
            namespace: helse-arbeidsgiver-alerts # required
            severity: critical