apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: helse-arbeidsgiver-alerts-dev-gcp
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  receivers:
    slack:
      channel: '#helse-arbeidsgiver-alerts'
  groups:
    - name: Applikasjon nede
      rules:
        - alert: Tester alerts for PrometheusRule
          expr: sum by (app, container, pod, namespace) (floor(increase(logback_events_total{app="im-api", level="info"} [3m]))) > 0
          for: 5m
          labels:
            namespace: helsearbeidsgiver
            severity: info