apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prod-gcp-alerts
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  groups:
    - name: prod-gcp-alerts
      rules:
        - alert: app-nede
          expr: kube_deployment_status_replicas_available{namespace="helsearbeidsgiver"} == 0
          for: 2m
          annotations:
            consequence: '*\{{ $labels.deployment }}* er nede!'
            action: "`kubectl describe pod <podname>` -> `kubectl logs <podname>`"
            summary: |-
              This is a multi-line summary with
              linebreaks and everything. Here you can give a more detailed
              summary of what this alert is about
          labels:
            namespace: helsearbeidsgiver # required
            severity: critical
        - alert: kontinuerlig-restart
          expr: sum(increase(kube_pod_container_status_restarts_total{namespace="helsearbeidsgiver"}[30m])) by (container) > 2
          for: 5m
          annotations:
            consequence: Applikasjonen restarter for ofte
            action: "`kubectl describe pod <podname>` -> `kubectl logs <podname>`"
            summary: |-
              This is a multi-line summary with
              linebreaks and everything. Here you can give a more detailed
              summary of what this alert is about
          labels:
            namespace: helsearbeidsgiver # required
            severity: warning
        - alert: mange-feil
          expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_namespace="helsearbeidsgiver",log_level=~"Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_namespace="helsearbeidsgiver"}[3m]))) > 10
          for: 5m
          annotations:
            consequence: Applikasjonen har mange feil
            action: "`kubectl describe pod <podname>` -> `kubectl logs <podname>`"
            summary: |-
              This is a multi-line summary with
              linebreaks and everything. Here you can give a more detailed
              summary of what this alert is about
          labels:
            namespace: helsearbeidsgiver # required
            severity: warning
        - alert: mange-warnings
          expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_namespace="helsearbeidsgiver",log_level=~"Warning"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_namespace="helsearbeidsgiver"}[3m]))) > 10
          for: 5m
          annotations:
            consequence: Applikasjonen har mange feil
            action: "`kubectl describe pod <podname>` -> `kubectl logs <podname>`"
            summary: |-
              This is a multi-line summary with
              linebreaks and everything. Here you can give a more detailed
              summary of what this alert is about
          labels:
            namespace: helsearbeidsgiver # required
            severity: warning