name: Deploy alerts to NAIS
on:
  push:
    branches:
      - master
    paths:
      - 'prod-gcp.yaml'
      - 'prod-fss.yaml'
      - 'dev-gcp.yaml'
      - '.github/workflows/alerts.yml'
jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to PROD-GCP
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: prod-gcp.yaml
      - name: Deploy to DEV-GCP
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: dev-gcp.yaml
