name: Deploy alerts to NAIS
on:
  push:
    branches:
      - master
    paths:
      - 'prod-gcp.yaml'
      - 'prod-fss.yaml'
      - 'dev-gcp.yaml'
      - '.github/workflows/alerts.yml'
jobs:
  apply-alerts:
    name: Apply alerts to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to PROD-GCP
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: prod-gcp.yaml
      - name: Deploy to PROD-FSS
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: prod-fss.yaml
      - name: Deploy to DEV-GCP
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: dev-gcp.yaml